var fecha = new Date()
console.log("El año es: "+fecha.getFullYear())
console.log("El mes es: "+(fecha.getMonth()+1))
console.log("El día es: "+fecha.getDate())
console.log("La hora es: "+fecha.getHours())
console.log("El minuto es: "+fecha.getMinutes())
console.log("El segundo es: "+fecha.getSeconds())
